import { notFound } from 'next/navigation';
import {
  ChevronRight,
  Target,
  Cpu,
  ArrowDownToLine,
  ArrowUpFromLine,
  DollarSign,
  Sparkles,
  History,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import ScanLiveView from '@/components/scan/scan-live-view';
import { AI_BRAND } from '@/lib/finding-theme';
import type { ScanRecurrenceSummary, ScanSummary } from '@/lib/supabase/types';

function formatTokens(n: number | null | undefined): string {
  if (n == null) return '—';
  const v = Number(n);
  if (!Number.isFinite(v)) return '—';
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)}K`;
  return String(v);
}

interface Props {
  params: { id: string };
}

export default async function ScanDetailPage({ params }: Props) {
  const supabase = createClient();
  const { data: scan } = await supabase.from('scans').select('*').eq('id', params.id).single();
  if (!scan) notFound();

  const { data: targets } = await supabase
    .from('scan_targets')
    .select('*')
    .eq('scan_id', params.id);

  // Cross-scan recurrence roll-up (pillar 1 item 5). Returns null when
  // this scan has no recurring findings — UI hides the section.
  const { data: recurrenceData } = await supabase.rpc(
    'scan_recurrence_summary',
    { p_scan_id: params.id },
  );
  const recurrence = recurrenceData as ScanRecurrenceSummary | null;
  const summary = (scan.summary ?? null) as ScanSummary | null;

  return (
    <div className="space-y-6">
      <nav className="flex items-center gap-1.5 text-xs text-neutral-500">
        <Link href="/scans" className="transition-colors hover:text-neutral-300">
          Scans
        </Link>
        <ChevronRight className="h-3 w-3" />
        <span className="text-neutral-300">{scan.run_name}</span>
      </nav>

      <header className="space-y-3">
        <h1 className="text-3xl font-semibold tracking-tight text-neutral-50">{scan.run_name}</h1>
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5 text-xs text-neutral-400">
          <span className="rounded-md bg-neutral-900 px-2 py-0.5 font-medium ring-1 ring-neutral-800">
            {scan.scan_mode}
          </span>
          {scan.scope_mode && (
            <span className="rounded-md bg-neutral-900 px-2 py-0.5 font-medium ring-1 ring-neutral-800">
              {scan.scope_mode}
            </span>
          )}
          {scan.llm_provider && (
            <span className="font-mono">{scan.llm_provider}</span>
          )}
          {scan.created_at && (
            <span>{new Date(scan.created_at).toLocaleString()}</span>
          )}
        </div>
      </header>

      <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <StatTile
          icon={DollarSign}
          label="Cost"
          value={
            scan.total_cost != null && Number(scan.total_cost) > 0
              ? `$${Number(scan.total_cost).toFixed(4)}`
              : '$0.0000'
          }
          accent="amber"
        />
        <StatTile
          icon={ArrowDownToLine}
          label="Input tokens"
          value={formatTokens(scan.total_input_tokens)}
          accent="cyan"
        />
        <StatTile
          icon={ArrowUpFromLine}
          label="Output tokens"
          value={formatTokens(scan.total_output_tokens)}
          accent="violet"
        />
        <StatTile
          icon={Cpu}
          label="AI agents"
          value={scan.agents_count != null ? String(scan.agents_count) : '0'}
          hint="See what each one tested ↓"
          href="#agents"
          accent="emerald"
        />
      </section>

      <section className="rounded-xl border border-neutral-800/80 bg-neutral-900/30 p-4">
        <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-wider text-neutral-400">
          <Target className="h-3.5 w-3.5" strokeWidth={2} />
          Targets
        </div>
        <ul className="mt-3 space-y-1.5">
          {targets?.map((t) => (
            <li key={t.id} className="flex items-center gap-2 text-sm">
              <span className="rounded bg-neutral-900 px-1.5 py-0.5 font-mono text-[10.5px] text-neutral-400 ring-1 ring-neutral-800">
                {t.type}
              </span>
              <code className="font-mono text-neutral-200">{t.value}</code>
            </li>
          ))}
        </ul>
      </section>

      {scan.instruction_text && (
        <section className="rounded-xl border border-neutral-800/80 bg-neutral-900/20 p-4">
          <div className="text-[11px] font-semibold uppercase tracking-wider text-neutral-400">
            Instructions
          </div>
          <p className="mt-2 text-sm leading-relaxed text-neutral-300">{scan.instruction_text}</p>
        </section>
      )}

      {/* Plain-language scan summary (pillar 1 item 7). Generated by the
          worker post-triage; the JSONB on scans.summary persists between
          loads. Hidden until generated — non-summary scans render as
          before. The whole point is the screenshot-and-forward use case:
          calibrated honest tone, two short paragraphs, copyable. */}
      {summary && (
        <section className={`rounded-xl p-5 ${AI_BRAND.bgTint} ${AI_BRAND.ring}`}>
          <div className="mb-2.5 flex items-center gap-2">
            <Sparkles className={`h-3.5 w-3.5 ${AI_BRAND.iconColor}`} strokeWidth={2.25} />
            <h2 className={`text-[11px] font-semibold uppercase tracking-wider ${AI_BRAND.gradientText}`}>
              Scan summary
            </h2>
            <span className="text-[10.5px] text-neutral-500">
              {summary.stats.findings_total} finding{summary.stats.findings_total === 1 ? '' : 's'}
              {summary.stats.endpoints_touched > 0 &&
                ` · ${summary.stats.endpoints_touched} endpoint${summary.stats.endpoints_touched === 1 ? '' : 's'} touched`}
            </span>
          </div>
          <div className="whitespace-pre-wrap text-[13.5px] leading-relaxed text-neutral-200">
            {summary.text}
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-[10.5px] text-neutral-500">
            {summary.stats.fix_now > 0 && (
              <span className="rounded bg-rose-500/15 px-1.5 py-0.5 text-rose-200 ring-1 ring-rose-400/30">
                {summary.stats.fix_now} fix-now
              </span>
            )}
            {summary.stats.fix_soon > 0 && (
              <span className="rounded bg-orange-500/15 px-1.5 py-0.5 text-orange-200 ring-1 ring-orange-400/30">
                {summary.stats.fix_soon} fix-soon
              </span>
            )}
            {summary.stats.monitor > 0 && (
              <span className="rounded bg-amber-500/10 px-1.5 py-0.5 text-amber-200 ring-1 ring-amber-400/30">
                {summary.stats.monitor} monitor
              </span>
            )}
            {summary.stats.dismiss_or_fp > 0 && (
              <span className="rounded bg-zinc-700/50 px-1.5 py-0.5 text-zinc-300 ring-1 ring-zinc-600/40">
                {summary.stats.dismiss_or_fp} dismissed
              </span>
            )}
            <span className="ml-auto font-mono text-neutral-600">
              {summary.model.replace('gemini/', '')}
            </span>
          </div>
        </section>
      )}

      {/* Cross-scan recurrence roll-up (pillar 1 item 5). Surfaces
          finding_occurrences data that already lives in the DB; the
          per-finding timeline lives on each card, this is the scan-level
          aggregation that answers "what did this rescan do?". */}
      {recurrence && recurrence.total > 0 && (
        <section className="rounded-xl border border-neutral-800/80 bg-neutral-900/30 p-4">
          <div className="mb-2.5 flex items-center gap-2">
            <History className="h-3.5 w-3.5 text-neutral-400" strokeWidth={2.25} />
            <h2 className="text-[11px] font-semibold uppercase tracking-wider text-neutral-300">
              Re-checked from prior scans
            </h2>
            <span className="text-[10.5px] text-neutral-500">
              {recurrence.total} finding{recurrence.total === 1 ? '' : 's'}
            </span>
          </div>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            <RecurrenceTile label="Still active" count={recurrence.still_active} tone="amber" />
            <RecurrenceTile label="Fixed" count={recurrence.fixed} tone="emerald" />
            <RecurrenceTile label="Dismissed" count={recurrence.dismissed} tone="zinc" />
            <RecurrenceTile label="Reopened" count={recurrence.reopened} tone="rose" />
          </div>
        </section>
      )}

      <ScanLiveView
        scanId={params.id}
        initialStatus={scan.status}
        agentsCount={scan.agents_count ?? 0}
        initialHeartbeatAt={scan.last_heartbeat_at ?? null}
        initialCancelRequestedAt={scan.cancel_requested_at ?? null}
        initialErrorMessage={scan.error_message ?? null}
        initialExitCode={scan.exit_code ?? null}
      />
    </div>
  );
}

const ACCENTS = {
  amber: 'text-amber-300/90 ring-amber-500/20',
  cyan: 'text-cyan-300/90 ring-cyan-500/20',
  violet: 'text-violet-300/90 ring-violet-500/20',
  emerald: 'text-emerald-300/90 ring-emerald-500/20',
} as const;

function StatTile({
  icon: Icon,
  label,
  value,
  accent,
  hint,
  href,
}: {
  icon: LucideIcon;
  label: string;
  value: string;
  accent: keyof typeof ACCENTS;
  hint?: string;
  href?: string;
}) {
  const cls = ACCENTS[accent];
  const body = (
    <>
      <div className="flex items-center gap-1.5 text-[10.5px] font-semibold uppercase tracking-wider text-neutral-500">
        <Icon className={`h-3 w-3 ${cls.split(' ')[0]}`} strokeWidth={2.25} />
        {label}
      </div>
      <div className="mt-1.5 font-mono text-xl font-semibold tabular-nums text-neutral-100">
        {value}
      </div>
      {hint && (
        <div className="mt-1 text-[10.5px] leading-snug text-neutral-500 transition-colors group-hover:text-cyan-300/80">
          {hint}
        </div>
      )}
    </>
  );
  const wrapperCls =
    'group block rounded-xl border border-neutral-800/80 bg-neutral-900/30 px-4 py-3 transition-colors';
  if (href) {
    return (
      <Link href={href} className={`${wrapperCls} hover:border-neutral-700`}>
        {body}
      </Link>
    );
  }
  return <div className={wrapperCls}>{body}</div>;
}

const RECURRENCE_TONE: Record<string, string> = {
  amber: 'text-amber-300',
  emerald: 'text-emerald-300',
  zinc: 'text-neutral-400',
  rose: 'text-rose-300',
};

function RecurrenceTile({
  label,
  count,
  tone,
}: {
  label: string;
  count: number;
  tone: keyof typeof RECURRENCE_TONE;
}) {
  const dim = count === 0;
  return (
    <div className="rounded-md bg-neutral-900/60 px-2.5 py-2 ring-1 ring-neutral-800/80">
      <div
        className={`text-lg font-semibold tracking-tight ${
          dim ? 'text-neutral-700' : RECURRENCE_TONE[tone]
        }`}
      >
        {count}
      </div>
      <div className="mt-0.5 text-[10px] uppercase tracking-wider text-neutral-500">{label}</div>
    </div>
  );
}
